#!/usr/bin/env bash

FILE=$1
FORMAT="--out-format=xterm256"

hl(){
    highlight --syntax=$1 $FORMAT ${FILE}
}

if [[ -z ${FILE} ]]; then
    echo "No argument provided!"
    exit 1
fi

if [[ ! -f ${FILE} ]]; then
    echo "HCAT: $FILE is not a file"
    exit 1
fi

default_highlight(){
    highlight --force --out-format=xterm256 ${FILE}
}

#dirname=$(dirname $FILE)
base_name=$(basename ${FILE})

# ${string:position:length}
first_character="${base_name:0:1}"

if [[ ${first_character} == "." ]]; then # Dotfile
    if [[ $FILE == *"vim"* ]]; then
        # vimrc?
        hl vim
    else
        hl bash
    fi
elif  [[ ! ${base_name} == *"."* ]]; then # if name doesn't contain "." => has no extension
    #TODO: Read first line and scan for sh / bash / python / perl / lua
    shebang=$(head -1 ${FILE})

    case "$shebang" in
        *sh*)
            hl bash
            ;;

        *python*)
            hl py 
            ;;

        *lua*)
            hl lua
            ;;

        *node*)
            hl js
            ;;

        *perl*)
            hl perl
            ;;
        *)
            hl bash 
            ;;
    esac
else
    default_highlight
fi

