#!/usr/bin/env bash

extension1=$1
extension2=$2
extension3=$3

if [[ -z "${extension1// }" ]]; then
	echo "No extension given."
elif [[ -z "${extension2// }" ]]; then
	find . -name '*.'$extension1 | xargs wc -l
elif [[ -z "${extension3// }" ]]; then
	find . \( -name '*.'$extension1 -o -name '*.'$extension2 \) | xargs wc -l
else
	find . \( -name '*.'$extension1 -o -name '*.'$extension2 -o -name '*.'$extension3 \) | xargs wc -l
fi
